language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f ./backend/dockerfile.test -t pch0989/backend-test-app ./backend

script:
  - docker run pch0989/backend-test-app

after_success:
  - docker build -t pch0989/board-app-frontend ./frontend
  - docker build -t pch0989/board-app-backend ./backend
  - docker build -t pch0989/board-app-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push pch0989/board-app-frontend
  - docker push pch0989/board-app-backend
  - docker push pch0989/board-app-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
