version: "3"
services:
  frontend:
    container_name: frontend
    image: pch0989/board-app-frontend
    expose:
      - "3000"

  backend:
    container_name: backend
    image: pch0989/board-app-backend
    expose:
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: nginx
    restart: always
    image: pch0989/board-app-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
