version: "2.4"
services:
  frontend:
    container_name: frontend
    image: pch0989/board-app-frontend
    expose:
      - "3000"

  backend:
    container_name: backend
    image: pch0989/board-app-backend
    expose:
      - "5000"

  nginx:
    container_name: nginx
    restart: always
    image: pch0989/board-app-nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
