version: "2.4"
services:
  frontend:
    container_name: frontend
    image: pch0989/board-app-frontend
    expose:
      - "3000"
    environment:
      BASE_URL: $BASE_URL

  backend:
    container_name: backend
    image: pch0989/board-app-backend
    expose:
      - "5000"
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      COOKIE_SECRET: $COOKIE_SECRET
      JWT_SECRET: $JWT_SECRET

  nginx:
    container_name: nginx
    restart: always
    image: pch0989/board-app-nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
