version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"

  backend:
    container_name: backend
    build: ./backend
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  mysql:
    container_name: mysql
    build: ./mysql
    restart: unless-stopped
    expose:
      - "3306"
    # ports:
    #   - "3307:3306"
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
