version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: dockerfile.test
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=board-app
    command: sh -c "yarn seed && yarn dev"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    build: ../mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ../mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
