FROM node:alpine as builder
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY ./ ./
RUN ls -a
RUN yarn install
RUN yarn build

FROM node:16.14
WORKDIR /app
COPY package.json ./
RUN yarn install --production=true
COPY --from=builder /app/dist .
CMD ["node", "src/bootstrap.js"]